insert into Tasks (Name, Description) values ('Superficial foreign body, left lower leg, subs encntr', 'vitae ipsum aliquam non mauris');
insert into Tasks (Name, Description) values ('Squamous blepharitis unspecified eye, unspecified eyelid', 'diam nam tristique tortor eu');
insert into Tasks (Name, Description) values ('Poisoning by tetracyclines, undetermined, sequela', 'leo pellentesque');
insert into Tasks (Name, Description) values ('Breakdown (mechanical) of GI prosth dev/grft, sequela', 'massa volutpat');
insert into Tasks (Name, Description) values ('Macula scars of posterior pole (post-traumatic)', 'consequat ut');
insert into Tasks (Name, Description) values ('Osteolysis, right shoulder', 'ultricies eu nibh quisque id');
insert into Tasks (Name, Description) values ('Displaced pilon fracture of left tibia', 'ligula nec sem');
insert into Tasks (Name, Description) values ('Secondary hypertension, unspecified', 'maecenas tincidunt lacus at velit vivamus');
insert into Tasks (Name, Description) values ('Traumatic compartment syndrome of r low extrem, init', 'vitae nisl aenean lectus pellentesque eget');
insert into Tasks (Name, Description) values ('Chronic lobular hepatitis, not elsewhere classified', 'pellentesque eget');
insert into Tasks (Name, Description) values ('Unspecified superficial injury of oth part of neck, sequela', 'nec nisi volutpat eleifend donec ut');
insert into Tasks (Name, Description) values ('Animl-ridr or occ of anml-drn vehicle injured in trnsp acc', 'ut at');
insert into Tasks (Name, Description) values ('Premature separation of placenta with oth coagulation defect', 'convallis morbi odio');
insert into Tasks (Name, Description) values ('Mech compl of artif skin grft /decellular alloderm, subs', 'ac nulla sed vel enim');
insert into Tasks (Name, Description) values ('Sedative, hypnotic or anxiolytic abuse w psychotic disorder', 'mauris eget massa');
insert into Tasks (Name, Description) values ('Genital varices in pregnancy, second trimester', 'ut volutpat');
insert into Tasks (Name, Description) values ('Radiological devices associated with adverse incidents', 'mauris eget massa tempor convallis nulla');
insert into Tasks (Name, Description) values ('Neoplasm of unspecified behavior of respiratory system', 'volutpat convallis morbi');
insert into Tasks (Name, Description) values ('Melanocytic nevi', 'faucibus orci');
insert into Tasks (Name, Description) values ('Driver of hv veh injured in clsn w unsp mv in traf, init', 'et magnis dis parturient');
insert into Tasks (Name, Description) values ('Inj muscle, fascia and tendon of left hip, subs encntr', 'venenatis non');
insert into Tasks (Name, Description) values ('Major depressive disorder, recurrent, in partial remission', 'mauris morbi non lectus');
insert into Tasks (Name, Description) values ('Oth disorders of bone development and growth, right shoulder', 'sit amet eros');
insert into Tasks (Name, Description) values ('Flail joint, right ankle and foot', 'platea dictumst');
insert into Tasks (Name, Description) values ('Nondisp fx of head of l rad, 7thJ', 'est quam pharetra magna ac');
insert into Tasks (Name, Description) values ('Unsp opn wnd unsp frnt wall of thrx w/o penet thor cav, sqla', 'ligula in lacus curabitur at ipsum');
insert into Tasks (Name, Description) values ('Laceration without foreign body of nose, subs encntr', 'ultrices phasellus');
insert into Tasks (Name, Description) values ('Lacerat unsp blood vessel at ank/ft level, right leg, subs', 'in blandit ultrices enim lorem');
insert into Tasks (Name, Description) values ('Laceration w fb of unsp finger w damage to nail, init', 'tempor convallis');
insert into Tasks (Name, Description) values ('Frequency of micturition', 'ut massa volutpat convallis');
insert into Tasks (Name, Description) values ('Unspecified injury of left shoulder and upper arm', 'vel nulla');
insert into Tasks (Name, Description) values ('Synovial hypertrophy, NEC, right ankle and foot', 'porttitor pede justo eu');
insert into Tasks (Name, Description) values ('Strain musc/tend peroneal grp at low leg lev, unsp leg, init', 'sagittis nam');
insert into Tasks (Name, Description) values ('Lacerat msl/fasc/tnd post grp at thi lev, left thigh, subs', 'libero convallis eget');
insert into Tasks (Name, Description) values ('Poisn by selective serotonin reuptake inhibtr, acc, subs', 'at velit');
insert into Tasks (Name, Description) values ('Cannabis dependence with cannabis-induced anxiety disorder', 'sapien iaculis congue vivamus metus arcu');
insert into Tasks (Name, Description) values ('Drown due to fall/jump fr burning water-skis, init', 'orci nullam molestie nibh in');
insert into Tasks (Name, Description) values ('Unsp fx head of unsp femr, 7thH', 'congue diam id ornare');
insert into Tasks (Name, Description) values ('Unsp fracture of second metacarpal bone, right hand, sequela', 'aliquam lacus morbi');
insert into Tasks (Name, Description) values ('Secondary malignant neoplasm of cerebral meninges', 'ligula in lacus curabitur at ipsum');
insert into Tasks (Name, Description) values ('Oth fx upr end unsp rad, 7thH', 'curae nulla dapibus dolor');
insert into Tasks (Name, Description) values ('Unspecified open wound, left lower leg, subsequent encounter', 'dis parturient montes nascetur ridiculus mus');
insert into Tasks (Name, Description) values ('Other chronic osteomyelitis, unspecified radius and ulna', 'tortor duis mattis egestas');
insert into Tasks (Name, Description) values ('Spondylolysis, thoracic region', 'donec pharetra magna vestibulum aliquet ultrices');
insert into Tasks (Name, Description) values ('Injury of nerve root of cervical spine, sequela', 'cursus vestibulum');
insert into Tasks (Name, Description) values ('Open bite of r bk wl of thorax w penet thor cavity, sequela', 'turpis integer aliquet massa id lobortis');
insert into Tasks (Name, Description) values ('Other dermatopolymyositis with respiratory involvement', 'etiam faucibus cursus');
insert into Tasks (Name, Description) values ('Flail joint, unspecified joint', 'tristique in tempus sit amet sem');
insert into Tasks (Name, Description) values ('Hereditary hemorrhagic telangiectasia', 'aliquam non mauris morbi non lectus');
insert into Tasks (Name, Description) values ('Other specified disorders of amniotic fluid and membranes', 'donec posuere');
insert into Tasks (Name, Description) values ('Other bursitis, not elsewhere classified, right hip', 'platea dictumst maecenas ut massa');
insert into Tasks (Name, Description) values ('Military operations involving unsp destruction of aircraft', 'convallis nunc proin at');
insert into Tasks (Name, Description) values ('Periprosth fracture around internal prosth r knee jt, subs', 'lobortis vel dapibus at diam');
insert into Tasks (Name, Description) values ('Unsp fx shaft of left tibia, subs for clos fx w malunion', 'ullamcorper purus sit amet');
insert into Tasks (Name, Description) values ('Minimal keratinized residual ridge mucosa', 'quisque porta volutpat');
insert into Tasks (Name, Description) values ('Other specified injury of thoracic aorta, subs encntr', 'euismod scelerisque quam');
insert into Tasks (Name, Description) values ('Sltr-haris Type III physeal fx phalanx of right toe, sequela', 'turpis elementum');
insert into Tasks (Name, Description) values ('Strain of musc/fasc/tend at shldr/up arm, unsp arm', 'at nulla');
insert into Tasks (Name, Description) values ('Toxic effect of chewing tobacco, intentional self-harm', 'augue luctus tincidunt nulla mollis molestie');
insert into Tasks (Name, Description) values ('Nondisplaced fracture of lateral malleolus of right fibula', 'sociis natoque penatibus');
insert into Tasks (Name, Description) values ('Oth fx upr & low end l fibula, 7thN', 'etiam justo etiam pretium');
insert into Tasks (Name, Description) values ('Laceration w fb of r mid finger w/o damage to nail, init', 'nec sem duis aliquam convallis nunc');
insert into Tasks (Name, Description) values ('Pnctr w/o foreign body of unsp cheek and TMJ area, sequela', 'arcu libero');
insert into Tasks (Name, Description) values ('Congenital absence of both forearm and hand', 'molestie hendrerit at vulputate vitae nisl');
insert into Tasks (Name, Description) values ('Oth granulomatous disorders of the skin, subcu', 'tortor eu pede');
insert into Tasks (Name, Description) values ('Toxic effect of contact w Portugese Man-o-war, undetermined', 'neque sapien placerat ante nulla');
insert into Tasks (Name, Description) values ('Laceration of unsp quadriceps musc/fasc/tend, init', 'condimentum curabitur in');
insert into Tasks (Name, Description) values ('Occup of bus injured in collision w hv veh nontraf, init', 'sagittis dui vel nisl duis ac');
insert into Tasks (Name, Description) values ('Osteonecrosis due to drugs, left ankle', 'mauris enim leo rhoncus sed');
insert into Tasks (Name, Description) values ('Displaced spiral fracture of shaft of ulna, unsp arm, init', 'justo aliquam quis turpis eget elit');
insert into Tasks (Name, Description) values ('Infect/inflm reaction due to insulin pump, subs', 'non lectus aliquam');
insert into Tasks (Name, Description) values ('Other superficial bite of unspecified foot, subs encntr', 'luctus nec molestie sed justo');
insert into Tasks (Name, Description) values ('Disp fx of neck of fourth metacarpal bone, left hand', 'vestibulum ante ipsum primis in');
insert into Tasks (Name, Description) values ('Other and unspecified ovrexrtn or strnous move/pstr, init', 'nullam sit amet turpis elementum');
insert into Tasks (Name, Description) values ('Nondisp fx of dist phalanx of l rng fngr, 7thK', 'nisi nam');
insert into Tasks (Name, Description) values ('Oth injury of unspecified vertebral artery, sequela', 'sociis natoque');
insert into Tasks (Name, Description) values ('Exophthalmic conditions', 'luctus et ultrices posuere');
insert into Tasks (Name, Description) values ('Abscess of bursa', 'in leo maecenas pulvinar lobortis');
insert into Tasks (Name, Description) values ('Activity, baseball', 'sapien cum sociis natoque penatibus et');
insert into Tasks (Name, Description) values ('Other failed induction of labor', 'eleifend pede libero quis');
insert into Tasks (Name, Description) values ('Polycythemia vera', 'dis parturient montes');
insert into Tasks (Name, Description) values ('Other secondary thrombocytopenia', 'dui vel nisl duis ac nibh');
insert into Tasks (Name, Description) values ('Encounter for issue of repeat prescription', 'proin eu');
insert into Tasks (Name, Description) values ('Other subluxation of unspecified shoulder joint, init encntr', 'pellentesque ultrices');
insert into Tasks (Name, Description) values ('Panniculitis aff regions of neck/bk, cervicothor region', 'nisl duis ac nibh');
insert into Tasks (Name, Description) values ('Type 2 diab with prolif diab rtnop with macular edema, l eye', 'pretium iaculis diam erat fermentum justo');
insert into Tasks (Name, Description) values ('Otosclerosis involving oval window, obliterative, bilateral', 'arcu libero');
insert into Tasks (Name, Description) values ('Dislocation of distal interphalangeal joint of other finger', 'id turpis integer aliquet massa');
insert into Tasks (Name, Description) values ('Nondisplaced transcondylar fracture of unspecified humerus', 'sed vel');
insert into Tasks (Name, Description) values ('Sltr-haris Type II physeal fx upper end of r fibula, init', 'urna ut tellus nulla ut erat');
insert into Tasks (Name, Description) values ('Vitreous abscess (chronic)', 'sem duis aliquam');
insert into Tasks (Name, Description) values ('Sublux of MC (bone), proximal end of unsp hand, sequela', 'curabitur gravida');
insert into Tasks (Name, Description) values ('Complete traumatic transphalangeal amputation of thmb, subs', 'placerat ante nulla justo aliquam quis');
insert into Tasks (Name, Description) values ('Nondisp seg fx shaft of ulna, l arm, 7thG', 'ac lobortis vel dapibus at');
insert into Tasks (Name, Description) values ('Contact w hot household appliance, undet intent, sequela', 'at nibh in hac habitasse platea');
insert into Tasks (Name, Description) values ('Scombroid fish poisoning, accidental, sequela', 'dolor vel est donec');
insert into Tasks (Name, Description) values ('SARS-associated coronavirus causing diseases classd elswhr', 'ipsum integer');
insert into Tasks (Name, Description) values ('Sltr-haris Type I physl fx low end humer, r arm, 7thK', 'a ipsum integer a nibh in');
insert into Tasks (Name, Description) values ('Unsp pedl cyclst injured in clsn w 2/3-whl mv nontraf, subs', 'a libero nam dui');
insert into Tasks (Name, Description) values ('Poisoning by cocaine, accidental (unintentional), subs', 'sapien in sapien iaculis congue vivamus');
